use crate::olarm_api::models::device_profile::DeviceProfile;
use crate::olarm_api::models::device_state::DeviceState;
use crate::olarm_api::models::device_triggers::DeviceTriggers;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone)]
pub struct UserResponse {
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "userIndex")]
    pub user_index: i64,
    #[serde(rename = "xeroContactId")]
    pub xero_contact_id: String,
    #[serde(rename = "oauthLinkPrompt")]
    pub oauth_link_prompt: bool,
    #[serde(rename = "oauthIsFederated")]
    pub oauth_is_federated: bool,
    #[serde(rename = "oauthIsLinked")]
    pub oauth_is_linked: bool,
    #[serde(rename = "oauthProvider")]
    pub oauth_provider: String,
    #[serde(rename = "entityIndex")]
    pub entity_index: i64,
    #[serde(rename = "entityName")]
    pub entity_name: String,
    #[serde(rename = "entityLogo")]
    pub entity_logo: String,
    #[serde(rename = "entityBadgeSize1")]
    pub entity_badge_size1: i64,
    #[serde(rename = "userType")]
    pub user_type: String,
    #[serde(rename = "userStatus")]
    pub user_status: String,
    #[serde(rename = "userNotice")]
    pub user_notice: String,
    #[serde(rename = "userFirstname")]
    pub user_firstname: String,
    #[serde(rename = "userSurname")]
    pub user_surname: String,
    #[serde(rename = "userFullname")]
    pub user_fullname: String,
    #[serde(rename = "userPin")]
    pub user_pin: String,
    #[serde(rename = "userEmail")]
    pub user_email: String,
    #[serde(rename = "userPhone")]
    pub user_phone: String,
    #[serde(rename = "userCreated")]
    pub user_created: i64,
    #[serde(rename = "userDistributor")]
    pub user_distributor: i64,
    #[serde(rename = "userAdmin")]
    pub user_admin: i64,
    #[serde(rename = "userResponse")]
    pub user_response: i64,
    #[serde(rename = "userBetaProgram")]
    pub user_beta_program: i64,
    #[serde(rename = "userNpsSurveyTimeS")]
    pub user_nps_survey_time_s: i64,
    #[serde(rename = "userRegions")]
    pub user_regions: String,
    #[serde(rename = "countryIndex")]
    pub country_index: i64,
    #[serde(rename = "countryNiceName")]
    pub country_nice_name: String,
    #[serde(rename = "countryPhoneCode")]
    pub country_phone_code: i64,
    pub devices: Vec<UserDevice>,
    #[serde(rename = "userNoticeHeaderCustom")]
    pub user_notice_header_custom: String,
    #[serde(rename = "userNoticeMsgCustom")]
    pub user_notice_msg_custom: String,
    #[serde(rename = "userNpsSurveyPrompt")]
    pub user_nps_survey_prompt: i64,
    #[serde(rename = "termsUrl")]
    pub terms_url: String,
    #[serde(rename = "popiUrl")]
    pub popi_url: String,
}
#[derive(Serialize, Deserialize)]
struct Struct2 {
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "userIndex")]
    pub user_index: i64,
    #[serde(rename = "userEmail")]
    pub user_email: String,
    #[serde(rename = "userFirstname")]
    pub user_firstname: String,
    #[serde(rename = "userSurname")]
    pub user_surname: String,
    #[serde(rename = "userWebhookURL")]
    pub user_webhook_url: String,
    #[serde(rename = "userWebhookSecret")]
    pub user_webhook_secret: String,
    #[serde(rename = "linkCreated")]
    pub link_created: i64,
    #[serde(rename = "linkStarts")]
    pub link_starts: i64,
    #[serde(rename = "linkExpires")]
    pub link_expires: i64,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct User {
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "userIndex")]
    pub user_index: i64,
    #[serde(rename = "userEmail")]
    pub user_email: String,
    #[serde(rename = "userFirstname")]
    pub user_firstname: String,
    #[serde(rename = "userSurname")]
    pub user_surname: String,
    #[serde(rename = "userWebhookURL")]
    pub user_webhook_url: String,
    #[serde(rename = "userWebhookSecret")]
    pub user_webhook_secret: String,
    #[serde(rename = "linkCreated")]
    pub link_created: i64,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct Response {
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "userIndex")]
    pub user_index: i64,
    #[serde(rename = "userEmail")]
    pub user_email: String,
    #[serde(rename = "userFirstname")]
    pub user_firstname: String,
    #[serde(rename = "userSurname")]
    pub user_surname: String,
    #[serde(rename = "linkCreated")]
    pub link_created: i64,
    #[serde(rename = "entityId")]
    pub entity_id: String,
    #[serde(rename = "entityIndex")]
    pub entity_index: i64,
    #[serde(rename = "entityName")]
    pub entity_name: String,
    #[serde(rename = "entityType")]
    pub entity_type: String,
    #[serde(rename = "entityEnCertified")]
    pub entity_en_certified: i64,
    #[serde(rename = "entityLogo")]
    pub entity_logo: String,
    #[serde(rename = "entityPhone")]
    pub entity_phone: String,
    #[serde(rename = "entityEmail")]
    pub entity_email: String,
    #[serde(rename = "entityAppEnable")]
    pub entity_app_enable: i64,
    #[serde(rename = "entityAppEnable2")]
    pub entity_app_enable2: i64,
    #[serde(rename = "entityBgColour")]
    pub entity_bg_colour: String,
    #[serde(rename = "entityTextColour")]
    pub entity_text_colour: String,
    #[serde(rename = "entityBgSize1")]
    pub entity_bg_size1: i64,
    #[serde(rename = "entityBgSize2")]
    pub entity_bg_size2: i64,
    #[serde(rename = "entityBgSpacer1")]
    pub entity_bg_spacer1: i64,
    #[serde(rename = "entityPanicEnable")]
    pub entity_panic_enable: i64,
    #[serde(rename = "entityPanicLocationEnable")]
    pub entity_panic_location_enable: i64,
    #[serde(rename = "entityCancelEnable")]
    pub entity_cancel_enable: i64,
    #[serde(rename = "entityDirectBilling")]
    pub entity_direct_billing: i64,
    #[serde(rename = "entityLock")]
    pub entity_lock: i64,
    #[serde(rename = "entityDeviceControl")]
    pub entity_device_control: i64,
    #[serde(rename = "entityIOControl")]
    pub entity_iocontrol: i64,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct Users {
    pub ver: i64,
    pub response: Response,
    pub primary: User,
    pub secondary: Vec<User>,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct UserDevice {
    pub id: String,
    pub index: i64,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "typeIs4G")]
    pub type_is4g: bool,
    pub name: String,
    #[serde(rename = "alarmType")]
    pub alarm_type: String,
    #[serde(rename = "alarmTypeDetail")]
    pub alarm_type_detail: String,
    pub lock: i64,
    #[serde(rename = "IMEI")]
    pub imei: String,
    pub serial: String,
    pub signal: i64,
    pub signal2: i64,
    #[serde(rename = "masterCode")]
    pub master_code: String,
    pub timestamp: i64,
    pub status: String,
    pub state: DeviceState,
    pub users: Users,
    pub profile: DeviceProfile,
    pub triggers: DeviceTriggers,
    #[serde(rename = "simDual")]
    pub sim_dual: i64,
    #[serde(rename = "simSelect")]
    pub sim_select: i64,
    pub firmware: String,
    #[serde(rename = "CCTV")]
    pub cctv: i64,
    #[serde(rename = "receiverNumExist")]
    pub receiver_num_exist: i64,
    #[serde(rename = "billingStatus")]
    pub billing_status: String,
    pub timezone: String,
    #[serde(rename = "gsmStamp")]
    pub gsm_stamp: i64,
    #[serde(rename = "wifiStamp")]
    pub wifi_stamp: i64,
    #[serde(rename = "wifiStatus")]
    pub wifi_status: String,
    #[serde(rename = "wifiConnected")]
    pub wifi_connected: i64,
    #[serde(rename = "wifiSSID")]
    pub wifi_ssid: String,
    #[serde(rename = "wifiRSSI")]
    pub wifi_rssi: i64,
    #[serde(rename = "loraStamp")]
    pub lora_stamp: i64,
    #[serde(rename = "gsmAntenna")]
    pub gsm_antenna: String,
    #[serde(rename = "loraSpreadFactor")]
    pub lora_spread_factor: i64,
    #[serde(rename = "loraPayloadStamp")]
    pub lora_payload_stamp: i64,
}
